export const LOGIN = "LOGIN";
export const SET_TOKEN_ERROR = "SET_TOKEN_ERROR";
export const USER_LOGOUT = "USER_LOGOUT";
export const SET_ERROR = "SET_ERROR";

export const PUT_QUALIFICATION = "PUT_QUALIFICATION";

export const GET_TICKETS1 = "GET_TICKETS1";
export const GET_TICKETS2 = "GET_TICKETS2";
export const GET_TICKETS3 = "GET_TICKETS3";
export const GET_TICKETS4 = "GET_TICKETS4";
export const GET_TICKETS5 = "GET_TICKETS5";

export const GET_ANEXOS = "GET_ANEXOS";

export const GET_DOCUMENTWORKORDERMANTTO = "GET_DOCUMENTWORKORDERMANTTO";
